-- RUN THIS IN SUPABASE SQL EDITOR TO FIX "OFFLINE / ERROR FETCH"
-- This creates the missing table for the Finance features

CREATE TABLE IF NOT EXISTS public.financial_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  type text not null, -- 'gaji', 'bonus', 'thr', 'emas', 'pinjaman', 'pengeluaran'
  amount numeric default 0,
  description text,
  date timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Security
ALTER TABLE public.financial_records ENABLE ROW LEVEL SECURITY;

-- Allow Access
CREATE POLICY "Public Access" ON public.financial_records FOR ALL USING (true);

-- Ensure Notes has Color column too
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS color text;
