-- Copy and run this in your Supabase SQL Editor to set up the database

-- 1. Table for Catatan Kerja (Notes)
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Stores username or Supabase Auth UUID
  title text,
  content text,
  importance text default 'Normal',
  status text default 'Draft',
  color text, -- New: Store card color theme
  date text, -- Stored as string for simplicity to match local format
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Table for Keuangan (Legacy Monthly Data)
create table if not exists public.finance (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month int,
  gaji numeric default 0,
  bonus numeric default 0,
  thr numeric default 0,
  pengeluaran numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. NEW: Table for Keuangan (Transaction Based - Prompt Compliant)
create table if not exists public.financial_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  type text not null, -- 'gaji', 'bonus', 'thr', 'topup_emas', 'pinjaman'
  amount numeric default 0,
  description text,
  date timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Table for Pemahaman Bola (Articles)
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text,
  category text,
  content text,
  update_date text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Enable Row Level Security (RLS)
alter table public.notes enable row level security;
alter table public.finance enable row level security;
alter table public.financial_records enable row level security;
alter table public.articles enable row level security;

-- Policy: Allow all access for now (Simplest for "Personal" Dashboard)
create policy "Public Access" on public.notes for all using (true);
create policy "Public Access" on public.finance for all using (true);
create policy "Public Access" on public.financial_records for all using (true);
create policy "Public Access" on public.articles for all using (true);

-- 6. Table for Schedules (Jadwal Result)
create table if not exists public.schedules (
  id text primary key, -- Text ID to support 'manual-xxx' and 'master-xxx'
  user_id text not null,
  market_name text,
  days text,
  close_time text,
  open_time text,
  link text,
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

alter table public.schedules enable row level security;
create policy "Public Access" on public.schedules for all using (true);
